osx_image: xcode9.3
language: objective-c
script:
- "xcodebuild -project EventSource.xcodeproj -scheme EventSource -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.4' -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty"
after_success:
  - bash <(curl -s https://codecov.io/bash)